platform :ios, '15.0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Pianohack' do
  config = use_native_modules!

  # If you're using static frameworks
  use_frameworks! :linkage => :static

  # React Native path configuration
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enable Firebase as static framework
  $RNFirebaseAsStaticFramework = true

  # Enable Video Caching
  $RNVideoUseVideoCaching = true

  target 'PianohackTests' do
    inherit! :complete
    # Pods for testing can be added here if needed
  end

  post_install do |installer|
    # Ensure Xcode 14.3 compatibility
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false, # Enable or disable Mac Catalyst support
      # :ccache_enabled => true # Uncomment to enable ccache support
    )

    # Workaround for Xcode 14.3 issues, if any
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end
  end
end
